[params]
  enableGitalk = true
[params.Gitalk]
    clientID = "Ov23li5R82FSKDuNshyF" # 您刚才创建Github Application 的 Client ID
    clientSecret = "d1212945e42cc5a38dc9563baaabee7612237874" # 您刚才创建Github Application 的 Client Secret
    repo = "jayjd.github.io" # 您的博客的github地址Repository name，例如：xxxx.github.io
    owner = "jayjd" # 您的GitHub ID
    admin= "jayjd" # 您的GitHub ID
    id= location.pathname # 文章页面的链接地址就是ID
    labels= "gitalk" # Github issue labels. If you used to use Gitment, you can change it
    perPage= 15 # Pagination size, with maximum 100.
    pagerDirection= "last" # Comment sorting direction, available values are 'last' and 'first'.
    createIssueManually= true # 设置为true，如果是管理员登录，会自动创建issue，如果是false，需要管理员手动添加第一个评论(issue)
    distractionFreeMode= false # Enable hot key (cmd|ctrl + enter) submit comment.